/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianCamera
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/CameraModal.ts
var import_obsidian = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  saveMode: "fixed",
  fixedFolderPath: "attachments/snaps",
  relativeSubfolderName: "images",
  imageQuality: "png",
  imageResolution: "original",
  insertFormat: "wikilink"
};
var IMAGE_QUALITY_MAP = {
  "png": { label: "\u65E0\u635F (PNG)", mimeType: "image/png", quality: 1, ext: "png" },
  "jpeg-high": { label: "\u9AD8\u8D28\u91CF (JPEG 95%)", mimeType: "image/jpeg", quality: 0.95, ext: "jpg" },
  "jpeg-medium": { label: "\u4E2D\u7B49 (JPEG 80%)", mimeType: "image/jpeg", quality: 0.8, ext: "jpg" },
  "jpeg-low": { label: "\u4F4E\u8D28\u91CF (JPEG 60%)", mimeType: "image/jpeg", quality: 0.6, ext: "jpg" }
};
var IMAGE_RESOLUTION_MAP = {
  "original": { label: "\u539F\u59CB\u5206\u8FA8\u7387", maxWidth: 0 },
  "1080p": { label: "1080p (FHD)", maxWidth: 1920 },
  "720p": { label: "720p (HD)", maxWidth: 1280 },
  "480p": { label: "480p (SD)", maxWidth: 854 }
};

// src/CameraModal.ts
var STYLE_ID = "obsidian-camera-styles";
var STYLES = `
.ocam-wrapper {
  display: flex; flex-direction: column;
  background: #111827; color: #f3f4f6;
  border-radius: 12px; overflow: hidden; min-width: 300px;
}
/* \u2500\u2500 Video area \u2500\u2500 */
.ocam-video-area {
  position: relative; background: #000;
  display: flex; align-items: center; justify-content: center;
}
.ocam-video-area video {
  width: 100%; max-height: 58vh;
  display: block; object-fit: cover;
}
.ocam-flash {
  position: absolute; inset: 0; background: #fff;
  opacity: 0; pointer-events: none;
}
.ocam-badge {
  position: absolute; display: flex; align-items: center; gap: 5px;
  padding: 3px 10px; border-radius: 99px; font-size: 12px; font-weight: 600;
  background: rgba(0,0,0,0.55); backdrop-filter: blur(4px);
}
.ocam-live-badge { top: 10px; right: 10px; color: #4ade80; }
.ocam-rec-badge  { top: 10px; left: 10px;  color: #f87171; opacity: 0; transition: opacity .3s; }
.ocam-rec-badge.show { opacity: 1; }
.ocam-pulse {
  width: 8px; height: 8px; border-radius: 50%;
  background: currentColor; animation: ocam-blink 1s infinite;
}
@keyframes ocam-blink { 0%,100%{opacity:1} 50%{opacity:.2} }
/* \u2500\u2500 Controls bar \u2500\u2500 */
.ocam-controls {
  display: flex; align-items: center; justify-content: center;
  gap: 10px; padding: 12px 16px; flex-wrap: wrap;
  background: rgba(255,255,255,0.03);
  border-top: 1px solid rgba(255,255,255,0.07);
}
.ocam-btn {
  display: flex; flex-direction: column; align-items: center; gap: 3px;
  cursor: pointer; padding: 9px 14px; border-radius: 10px; min-width: 66px;
  border: 1px solid rgba(255,255,255,0.1); background: rgba(255,255,255,0.05);
  color: #d1d5db; transition: all .18s ease; user-select: none;
  -webkit-tap-highlight-color: transparent;
}
.ocam-btn:hover  { background: rgba(255,255,255,0.12); color: #fff; transform: translateY(-1px); border-color: rgba(255,255,255,0.22); }
.ocam-btn:active { transform: translateY(0); }
.ocam-btn[disabled] { opacity: .35; cursor: not-allowed; transform: none !important; }
.ocam-btn .icon  { font-size: 20px; line-height: 1; }
.ocam-btn .lbl   { font-size: 10px; }
.ocam-btn-snap   { border-color: rgba(255,255,255,0.2); background: rgba(255,255,255,0.09); }
.ocam-btn-record.recording { background: rgba(239,68,68,.18); border-color: #ef4444; color: #fca5a5; }
/* Upload row */
.ocam-upload-row {
  display: flex; justify-content: center;
  padding: 6px 16px 14px; background: transparent;
}
.ocam-upload-lbl {
  cursor: pointer; display: inline-flex; align-items: center; gap: 5px;
  padding: 6px 16px; border-radius: 99px; font-size: 12px;
  color: rgba(255,255,255,.4); border: 1px solid rgba(255,255,255,.13);
  transition: all .18s ease;
}
.ocam-upload-lbl:hover { color: rgba(255,255,255,.75); background: rgba(255,255,255,.07); border-color: rgba(255,255,255,.25); }
/* \u2500\u2500 Android UI \u2500\u2500 */
.ocam-android {
  background: #111827; color: #f3f4f6;
  padding: 20px 16px 24px; min-width: 280px;
}
.ocam-android-title {
  text-align: center; font-size: 17px; font-weight: 700;
  margin-bottom: 18px; color: #fff;
}
.ocam-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
.ocam-card {
  cursor: pointer; display: flex; flex-direction: column;
  align-items: center; justify-content: center; gap: 8px;
  padding: 20px 10px; border-radius: 14px;
  border: 1.5px solid rgba(255,255,255,.1);
  background: rgba(255,255,255,.04);
  transition: all .18s ease; color: #d1d5db;
  -webkit-tap-highlight-color: transparent; user-select: none;
}
.ocam-card:active { transform: scale(.95); }
.ocam-card .c-icon { font-size: 34px; }
.ocam-card .c-lbl  { font-size: 13px; font-weight: 600; text-align: center; }
.ocam-card .c-hint { font-size: 11px; color: rgba(255,255,255,.4); }
.ocam-card-photo { border-color:rgba(96,165,250,.4); background:rgba(96,165,250,.08); color:#93c5fd; }
.ocam-card-photo:hover { background:rgba(96,165,250,.16); border-color:rgba(96,165,250,.65); }
.ocam-card-video { border-color:rgba(248,113,113,.4); background:rgba(248,113,113,.08); color:#fca5a5; }
.ocam-card-video:hover { background:rgba(248,113,113,.16); border-color:rgba(248,113,113,.65); }
.ocam-card-gallery {
  grid-column: 1/-1; flex-direction: row; padding: 14px 20px;
  border-color:rgba(167,139,250,.3); background:rgba(167,139,250,.06); color:#c4b5fd;
  justify-content: center; gap: 10px;
}
.ocam-card-gallery:hover { background:rgba(167,139,250,.14); border-color:rgba(167,139,250,.55); }
.ocam-card-gallery .c-icon { font-size: 22px; }
.ocam-card-gallery .c-lbl  { font-size: 14px; }
`;
var CameraModal = class extends import_obsidian.Modal {
  constructor(app, settings) {
    super(app);
    this.stream = null;
    this.timerHandle = null;
    this.settings = settings;
  }
  async onOpen() {
    this.injectStyles();
    this.contentEl.empty();
    const ok = await this.tryStream();
    if (ok)
      this.buildDesktopUI();
    else
      this.buildAndroidUI();
  }
  // ── Styles ──────────────────────────────────────────────────────────────────
  injectStyles() {
    if (!document.getElementById(STYLE_ID)) {
      const s = document.createElement("style");
      s.id = STYLE_ID;
      s.textContent = STYLES;
      document.head.appendChild(s);
    }
  }
  // ── Try getUserMedia ─────────────────────────────────────────────────────────
  async tryStream() {
    var _a;
    if (!((_a = navigator == null ? void 0 : navigator.mediaDevices) == null ? void 0 : _a.getUserMedia))
      return false;
    try {
      this.stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "environment" },
        audio: true
      });
      return true;
    } catch (e) {
      console.warn("[Camera] getUserMedia failed:", e);
      return false;
    }
  }
  // ── Resolve save path ────────────────────────────────────────────────────────
  getSavePath() {
    var _a, _b;
    if (this.settings.saveMode === "note-relative") {
      const f = this.app.workspace.getActiveFile();
      if (f) {
        const dir = (_b = (_a = f.parent) == null ? void 0 : _a.path) != null ? _b : "";
        const sub = (this.settings.relativeSubfolderName || "images").trim();
        return dir ? `${dir}/${sub}` : sub;
      }
    }
    return this.settings.fixedFolderPath || "attachments/snaps";
  }
  // ── Save to vault ────────────────────────────────────────────────────────────
  async saveFile(buf, isImage, name) {
    const qCfg = IMAGE_QUALITY_MAP[this.settings.imageQuality];
    const ext = isImage ? qCfg.ext : this.videoExt();
    if (!name) {
      const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      name = isImage ? `photo_${ts}.${ext}` : `video_${ts}.${ext}`;
    }
    const folder = (0, import_obsidian.normalizePath)(this.getSavePath());
    const path = (0, import_obsidian.normalizePath)(`${folder}/${name}`);
    new import_obsidian.Notice(`\u{1F4BE} Saving ${isImage ? "photo" : "video"}\u2026`);
    if (!this.app.vault.getAbstractFileByPath(folder))
      await this.app.vault.createFolder(folder);
    if (!this.app.vault.getAbstractFileByPath(path))
      await this.app.vault.createBinary(path, buf);
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) {
      new import_obsidian.Notice(`\u2705 Saved \u2192 ${path}`);
      this.close();
      return;
    }
    const ins = this.settings.insertFormat === "markdown" ? `![${name}](${path})
` : `![[${path}]]
`;
    view.editor.replaceRange(ins, view.editor.getCursor());
    new import_obsidian.Notice(`\u2705 ${isImage ? "Photo" : "Video"} inserted`);
    this.close();
  }
  // ── MIME helpers ─────────────────────────────────────────────────────────────
  videoMime() {
    var _a;
    if (typeof MediaRecorder === "undefined")
      return "";
    const list = [
      "video/webm;codecs=vp9,opus",
      "video/webm;codecs=vp8,opus",
      "video/webm",
      "video/mp4;codecs=h264,aac",
      "video/mp4"
    ];
    return (_a = list.find((t) => MediaRecorder.isTypeSupported(t))) != null ? _a : "";
  }
  videoExt() {
    return this.videoMime().includes("mp4") ? "mp4" : "webm";
  }
  // ── Draw snapshot to canvas (with optional resize) ───────────────────────────
  snapCanvas(video) {
    const resCfg = IMAGE_RESOLUTION_MAP[this.settings.imageResolution];
    let w = video.videoWidth, h = video.videoHeight;
    if (resCfg.maxWidth > 0 && w > resCfg.maxWidth) {
      h = Math.round(h * resCfg.maxWidth / w);
      w = resCfg.maxWidth;
    }
    const c = document.createElement("canvas");
    c.width = w;
    c.height = h;
    c.getContext("2d").drawImage(video, 0, 0, w, h);
    return c;
  }
  // ── Desktop UI ───────────────────────────────────────────────────────────────
  buildDesktopUI() {
    const root = this.contentEl.createDiv({ cls: "ocam-wrapper" });
    const area = root.createDiv({ cls: "ocam-video-area" });
    const vid = area.createEl("video");
    vid.autoplay = true;
    vid.muted = true;
    vid.setAttribute("playsinline", "true");
    vid.srcObject = this.stream;
    const flash = area.createDiv({ cls: "ocam-flash" });
    const liveBadge = area.createDiv({ cls: "ocam-badge ocam-live-badge" });
    liveBadge.createDiv({ cls: "ocam-pulse" });
    liveBadge.createSpan({ text: "LIVE" });
    const recBadge = area.createDiv({ cls: "ocam-badge ocam-rec-badge" });
    recBadge.createDiv({ cls: "ocam-pulse" });
    const recTimer = recBadge.createSpan({ text: "\u25CF REC 00:00" });
    const controls = root.createDiv({ cls: "ocam-controls" });
    const mkBtn = (icon, lbl, extra = "") => {
      const b = controls.createDiv({ cls: `ocam-btn ${extra}` });
      b.createSpan({ cls: "icon", text: icon });
      b.createSpan({ cls: "lbl", text: lbl });
      return b;
    };
    const switchBtn = mkBtn("\u{1F504}", "Switch");
    const snapBtn = mkBtn("\u{1F4F8}", "Photo", "ocam-btn-snap");
    const recBtn = mkBtn("\u23FA", "Record", "ocam-btn-record");
    if (typeof MediaRecorder === "undefined")
      recBtn.style.display = "none";
    const upRow = root.createDiv({ cls: "ocam-upload-row" });
    const upInp = upRow.createEl("input");
    upInp.type = "file";
    upInp.accept = "image/*,video/*";
    upInp.style.display = "none";
    upInp.id = "ocam-up";
    const upLbl = upRow.createEl("label", { cls: "ocam-upload-lbl", text: "\u2B06 Upload from device" });
    upLbl.htmlFor = "ocam-up";
    upLbl.appendChild(upInp);
    upInp.onchange = async () => {
      var _a;
      const f = (_a = upInp.files) == null ? void 0 : _a[0];
      if (!f)
        return;
      this.saveFile(await f.arrayBuffer(), f.type.startsWith("image/"), f.name.replace(/ /g, "-"));
    };
    let cameras = [];
    let camIdx = 0;
    navigator.mediaDevices.enumerateDevices().then((devs) => {
      var _a, _b, _c;
      cameras = devs.filter((d) => d.kind === "videoinput");
      if (cameras.length <= 1)
        switchBtn.style.display = "none";
      const sid = (_c = (_b = (_a = this.stream) == null ? void 0 : _a.getVideoTracks()[0]) == null ? void 0 : _b.getSettings()) == null ? void 0 : _c.deviceId;
      const i = cameras.findIndex((c) => c.deviceId === sid);
      if (i >= 0)
        camIdx = i;
    });
    const getStream = async (idx) => {
      const cam = cameras[idx];
      const c = (cam == null ? void 0 : cam.deviceId) ? { video: { deviceId: { exact: cam.deviceId } }, audio: true } : { video: { facingMode: idx === 0 ? "environment" : "user" }, audio: true };
      return navigator.mediaDevices.getUserMedia(c).catch(() => null);
    };
    switchBtn.onclick = async () => {
      var _a;
      camIdx = (camIdx + 1) % (cameras.length || 2);
      (_a = this.stream) == null ? void 0 : _a.getTracks().forEach((t) => t.stop());
      this.stream = await getStream(camIdx);
      if (this.stream) {
        vid.srcObject = this.stream;
        vid.play();
      }
    };
    snapBtn.onclick = () => {
      flash.style.transition = "none";
      flash.style.opacity = "1";
      requestAnimationFrame(() => {
        flash.style.transition = "opacity .45s ease";
        flash.style.opacity = "0";
      });
      const qCfg = IMAGE_QUALITY_MAP[this.settings.imageQuality];
      this.snapCanvas(vid).toBlob(async (blob) => {
        if (!blob)
          return;
        this.saveFile(await blob.arrayBuffer(), true);
      }, qCfg.mimeType, qCfg.quality);
    };
    const chunks = [];
    let recorder = null;
    recBtn.onclick = async () => {
      const getIcon = () => recBtn.querySelector(".icon");
      const getLbl = () => recBtn.querySelector(".lbl");
      if (!recorder && this.stream) {
        const mime = this.videoMime();
        try {
          recorder = new MediaRecorder(this.stream, mime ? { mimeType: mime } : {});
        } catch (e) {
          try {
            recorder = new MediaRecorder(this.stream);
          } catch (e2) {
            new import_obsidian.Notice("\u274C \u6B64\u8BBE\u5907\u4E0D\u652F\u6301\u5F55\u5236");
            return;
          }
        }
      }
      if (!recorder)
        return;
      const isRec = recorder.state === "recording";
      if (isRec) {
        recorder.stop();
        this.stopTimer();
        recBadge.classList.remove("show");
        recBtn.classList.remove("recording");
        getIcon().textContent = "\u23FA";
        getLbl().textContent = "Record";
        switchBtn.removeAttribute("disabled");
      } else {
        chunks.length = 0;
        recorder.start();
        recBadge.classList.add("show");
        recBtn.classList.add("recording");
        getIcon().textContent = "\u23F9";
        getLbl().textContent = "Stop";
        switchBtn.setAttribute("disabled", "true");
        this.startTimer(Date.now(), recTimer);
        recorder.ondataavailable = (e) => {
          var _a;
          if (((_a = e.data) == null ? void 0 : _a.size) > 0)
            chunks.push(e.data);
        };
        recorder.onstop = async () => {
          const mime = recorder.mimeType || this.videoMime() || "video/webm";
          const blob = new Blob(chunks, { type: mime });
          this.saveFile(await blob.arrayBuffer(), false);
        };
      }
    };
  }
  // ── Android fallback UI ──────────────────────────────────────────────────────
  buildAndroidUI() {
    const root = this.contentEl.createDiv({ cls: "ocam-android" });
    root.createDiv({ cls: "ocam-android-title", text: "\u{1F4F7} Camera" });
    const grid = root.createDiv({ cls: "ocam-grid" });
    const addCard = (parent, icon, lbl, hint, cls, accept, capture, isImage) => {
      const inp = parent.createEl("input");
      inp.type = "file";
      inp.accept = accept;
      if (capture)
        inp.capture = capture;
      inp.style.display = "none";
      const card = parent.createEl("label", { cls: `ocam-card ${cls}` });
      card.createSpan({ cls: "c-icon", text: icon });
      card.createSpan({ cls: "c-lbl", text: lbl });
      if (hint)
        card.createSpan({ cls: "c-hint", text: hint });
      card.appendChild(inp);
      inp.onchange = async () => {
        var _a;
        const f = (_a = inp.files) == null ? void 0 : _a[0];
        if (!f)
          return;
        const img = isImage !== null ? isImage : f.type.startsWith("image/");
        this.saveFile(await f.arrayBuffer(), img, f.name.replace(/ /g, "-"));
      };
    };
    addCard(grid, "\u{1F4F7}", "\u62CD\u6444\u7167\u7247", "Take Photo", "ocam-card-photo", "image/*", "camera", true);
    addCard(grid, "\u{1F3AC}", "\u5F55\u5236\u89C6\u9891", "Record Video", "ocam-card-video", "video/*", "camcorder", false);
    addCard(grid, "\u{1F5BC}\uFE0F", "\u4ECE\u76F8\u518C\u9009\u62E9", "", "ocam-card-gallery", "image/*,video/*", "", null);
  }
  // ── Timer helpers ────────────────────────────────────────────────────────────
  startTimer(start, el) {
    this.timerHandle = window.setInterval(() => {
      const s = Math.floor((Date.now() - start) / 1e3);
      const mm = String(Math.floor(s / 60)).padStart(2, "0");
      const ss = String(s % 60).padStart(2, "0");
      el.textContent = `\u25CF REC ${mm}:${ss}`;
    }, 1e3);
  }
  stopTimer() {
    if (this.timerHandle !== null) {
      clearInterval(this.timerHandle);
      this.timerHandle = null;
    }
  }
  onClose() {
    var _a;
    this.stopTimer();
    (_a = this.stream) == null ? void 0 : _a.getTracks().forEach((t) => t.stop());
    this.contentEl.empty();
  }
};

// src/SettingsTab.ts
var import_obsidian2 = require("obsidian");
var CameraSettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl: el } = this;
    el.empty();
    el.createEl("h2", { text: "\u{1F4F7} Camera Settings" });
    el.createEl("h3", { text: "\u{1F4C1} Save Location" });
    let fixedSetting;
    let relSetting;
    const updateVisibility = (mode) => {
      fixedSetting.settingEl.style.display = mode === "fixed" ? "" : "none";
      relSetting.settingEl.style.display = mode === "note-relative" ? "" : "none";
    };
    new import_obsidian2.Setting(el).setName("\u4FDD\u5B58\u6A21\u5F0F").setDesc("\u9009\u62E9\u6587\u4EF6\u4FDD\u5B58\u5230\u56FA\u5B9A\u76EE\u5F55\uFF0C\u8FD8\u662F\u5F53\u524D\u7B14\u8BB0\u6240\u5728\u76EE\u5F55\u7684\u5B50\u6587\u4EF6\u5939").addDropdown((dd) => dd.addOption("fixed", "\u{1F4C2} \u56FA\u5B9A\u76EE\u5F55").addOption("note-relative", "\u{1F4CE} \u5F53\u524D\u7B14\u8BB0\u76EE\u5F55\u4E0B\u7684\u5B50\u6587\u4EF6\u5939").setValue(this.plugin.settings.saveMode).onChange(async (val) => {
      this.plugin.settings.saveMode = val;
      await this.plugin.saveSettings();
      updateVisibility(val);
    }));
    fixedSetting = new import_obsidian2.Setting(el).setName("Fixed Folder Path").setDesc("Vault \u5185\u7684\u4FDD\u5B58\u8DEF\u5F84\uFF0C\u4F8B\u5982\uFF1Aattachments/snaps").addText((t) => t.setPlaceholder("attachments/snaps").setValue(this.plugin.settings.fixedFolderPath).onChange(async (val) => {
      this.plugin.settings.fixedFolderPath = val;
      await this.plugin.saveSettings();
    }));
    relSetting = new import_obsidian2.Setting(el).setName("\u5B50\u6587\u4EF6\u5939\u540D\u79F0").setDesc("\u5728\u5F53\u524D\u7B14\u8BB0\u6240\u5728\u76EE\u5F55\u4E0B\u521B\u5EFA\u7684\u5B50\u6587\u4EF6\u5939\u540D\uFF0C\u4F8B\u5982\uFF1Aimages").addText((t) => t.setPlaceholder("images").setValue(this.plugin.settings.relativeSubfolderName).onChange(async (val) => {
      this.plugin.settings.relativeSubfolderName = val;
      await this.plugin.saveSettings();
    }));
    updateVisibility(this.plugin.settings.saveMode);
    el.createEl("h3", { text: "\u{1F5BC}\uFE0F \u56FE\u7247\u8BBE\u7F6E" });
    new import_obsidian2.Setting(el).setName("\u56FE\u7247\u8D28\u91CF").setDesc("PNG \u4E3A\u65E0\u635F\u683C\u5F0F\uFF0CJPEG \u4F53\u79EF\u66F4\u5C0F\u3002\u4EC5\u5F71\u54CD\u62CD\u7167\uFF0C\u4E0D\u5F71\u54CD\u4E0A\u4F20\u6587\u4EF6").addDropdown((dd) => {
      Object.entries(IMAGE_QUALITY_MAP).forEach(([k, v]) => dd.addOption(k, v.label));
      return dd.setValue(this.plugin.settings.imageQuality).onChange(async (val) => {
        this.plugin.settings.imageQuality = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(el).setName("\u56FE\u7247\u5206\u8FA8\u7387").setDesc('\u62CD\u7167\u65F6\u7684\u6700\u5927\u5BBD\u5EA6\u9650\u5236\uFF08\u9009\u62E9"\u539F\u59CB\u5206\u8FA8\u7387"\u5219\u4E0D\u7F29\u653E\uFF09').addDropdown((dd) => {
      Object.entries(IMAGE_RESOLUTION_MAP).forEach(([k, v]) => dd.addOption(k, v.label));
      return dd.setValue(this.plugin.settings.imageResolution).onChange(async (val) => {
        this.plugin.settings.imageResolution = val;
        await this.plugin.saveSettings();
      });
    });
    el.createEl("h3", { text: "\u{1F4DD} \u63D2\u5165\u683C\u5F0F" });
    new import_obsidian2.Setting(el).setName("\u94FE\u63A5\u683C\u5F0F").setDesc("\u63D2\u5165\u7B14\u8BB0\u65F6\u4F7F\u7528\u7684\u683C\u5F0F").addDropdown((dd) => dd.addOption("wikilink", "Wikilink  ![[path]]").addOption("markdown", "Markdown  ![name](path)").setValue(this.plugin.settings.insertFormat).onChange(async (val) => {
      this.plugin.settings.insertFormat = val;
      await this.plugin.saveSettings();
    }));
  }
};

// src/main.ts
var ObsidianCamera = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("camera", "Obsidian Camera", () => {
      new CameraModal(this.app, this.settings).open();
    });
    this.addSettingTab(new CameraSettingsTab(this.app, this));
    this.addCommand({
      id: "open-camera-modal",
      name: "Open Camera / File Picker",
      callback: () => new CameraModal(this.app, this.settings).open()
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
